name: uoc20252pec3
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.10.6
  - jupyter=1.1.1
  - tqdm=4.67.1
  - scipy=1.16.2
  - scikit-learn=1.7.2
  - numpy=2.3.3
  - pip=24.2
  - python=3.12.12
  - kagglehub=0.3.4
  - pandas=2.3.3
  - seaborn=0.13.2
  - statsmodels=0.14.5
  - pip:
    - umap-learn==0.5.9.post2
    - ucimlrepo==0.0.7
